/run/initialize

#/control/execute macros/no_verbose.mac
/control/verbose 2
/run/verbose 2
/tracking/verbose 2

/vis/open VRML2FILE
#/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90. 180.
/vis/viewer/zoom 1.4

/vis/geometry/set/visibility Xenon 0 true

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu- cyan
/vis/modeling/trajectories/drawByParticleID-0/set opticalphoton none
/vis/scene/endOfEventAction accumulate


#/B1/gun/generator muon
/run/beamOn 1

/vis/viewer/flush

#/vis/viewer/set/visibility VacuumDet_sub5 0 false
